CREATE TABLE DIGISHOPS_STORE AS
(
ORDEN,
OPERACION,
TIPODEPEDIDO,
PRODUCTO,
SERIADO,
TRAFICA,
CUENTA,
LINEA,
NOMBREYAPELLIDO,
TIPO DOCUMENTO,
DOCUMENTO,
SEXO,
EDAD,
FECHADENACIMIENTO,
REGION,
NEGOCIO,
IDPEDIDOSTL,
REMITOSAP,
IDTRACKING,
FECHACREACION,
FECHADEACTIVACION,
ESTADO,
NTICKLERPEDECO,
SKU,
DESCRIPCIONSKU,
MARCA,
NIVELPRECIOPEDIDO,
NIVELPRECIOREAL,
VALIDACIONNIVELPRECIO,
PRECIOLISTASINIMP,
PRECIOLISTACONIMP,
SUBS3,
SUBS10,
SUBS1,
PRECIOFINAL,
TOTALFINANCIADO,
DIFPL-PO,
FORMADEPAGO,
CANTIDADDECUOTAS,
CANTIDADDECUOTASREAL,
TARJETA,
BANCO,
CODIGOAPROBACION,
FLAGCAMBIODEPLAN,
CODIGODEPLANORIGEN,
MONTOPLANORIGEN,
CODIGODEPLANDESTINO,
MONTOPLANDESTINO,
CAMBIODETIPODENEGOCIODESDEPP,
FECHADECAMBIODETIPODENEGOCIO,
RIESGO,
FECHACREACION,
FECHAACTIVACION,
TRACKID,
FECHAENTREGA,
HORAENTREGA,
NOMBRESUCURSAL,
TIPOVENTA,


CATEGORIACLAROCLUB,
IDPREMIO,
DESCRIPPREMIO,
PUNTOSPREMIO,
COSTOPREMIO,
PREMIOPENDIENTE,
PUNTOSDISPONIBLES,
RECEPTORALTERNATIVO,
ORIGEN,
RANGO SCORE,
PUNTOS SCORE
)

1.	"ORDEN";
2.	"OPERACION";
3.	"TIPO DE PEDIDO";
4.	"PRODUCTO";
5.	"SERIADO";
6.	"TRAFICA";
7.	"CUENTA";
8.	"LINEA";
9.	"NOMBRE Y APELLIDO";
10.	"TIPO DOCUMENTO";
11.	"DOCUMENTO";
12.	"SEXO";
13.	"EDAD";
14.	"FECHA DE NACIMIENTO";
15.	"REGION";
16.	"NEGOCIO";
17.	"ID PEDIDO STL";
18.	"REMITO SAP";
19.	"ID TRACKING";
20.	"FECHA CREACION";
21.	"FECHA DE ACTIVACION";
22.	"ESTADO";
23.	"N� TICKLER PEDECO";
24.	"SKU";
25.	" DESCRIPCION SKU";
26.	"MARCA";
27.	"NIVEL PRECIO PEDIDO";
28.	"NIVEL PRECIO REAL";
29.	"VALIDACION NIVEL PRECIO";
30.	"PRECIO LISTA SIN IMP";
31.	" PRECIO LISTA CON IMP";
32.	"SUBS3";
33.	"SUBS10";
34.	"SUBS1";
35.	"PRECIO FINAL";
36.	"TOTAL FINANCIADO";
37.	" DIF PL-PO";
38.	" FORMA DE PAGO";
39.	"CANTIDAD DE CUOTAS";
40.	"CANTIDAD DE CUOTAS REAL";
41.	"TARJETA";"BANCO";
42.	"CODIGO APROBACION";
43.	"FLAG CAMBIO DE PLAN ";
44.	"CODIGO DE PLAN ORIGEN ";
45.	"MONTO PLAN ORIGEN";
46.	"CODIGO DE PLAN DESTINO";
47.	"MONTO PLAN DESTINO";
48.	"CAMBIO DE TIPO DE NEGOCIO DESDE PP";
49.	"FECHA DE CAMBIO DE TIPO DE NEGOCIO";
50.	"RIESGO";
51.	"FECHA CREACION";
52.	"FECHA ACTIVACION";
53.	"TRACK ID";
54.	"FECHA ENTREGA";
55.	"HORA ENTREGA";
56.	"NOMBRE SUCURSAL";
57.	"TIPO VENTA";
58.	"CATEGORIA CLARO CLUB";
59.	"ID PREMIO";
60.	"DESCRIP PREMIO";
61.	"PUNTOS PREMIO";
62.	"COSTO PREMIO";
63.	"PREMIO PENDIENTE";
64.	"PUNTOS DISPONIBLES";
65.	"RECEPTOR ALTERNATIVO";
66.	"ORIGEN";
67.	"RANGO SCORE";
68.	"PUNTOS SCORE"


la suma de la funcion me da 51, 
