

GRANT SELECT ON EXC44585.MKT_DIG_CAMPANIAS_WA TO dracing;
GRANT SELECT ON EXC44585.AUX1_MKT_DIG_G4703 TO dracing;

GRANT SELECT ON EXC44585.MKT_DIG_TRAKING_WA TO dracing;
GRANT SELECT ON EXC44585.AUX1_TRAKING_WA_G4704 TO dracing;

SELECT * FROM EXC44585.MKT_DIG_CAMPANIAS_WA;
SELECT * FROM EXC44585.MKT_DIG_TRAKING_WA;

SELECT * FROM EXC44585.AUX1_MKT_DIG_G4703;
SELECT * FROM EXC44585.AUX1_TRAKING_WA_G4704;

SELECT * FROM DRACING.param_actualiz_racing
SELECT GRUPO, ACT_TABLE_NAME, ACT_PROCEDURE_NAME, ACT_ACT_TYPE, RTP_CODIGO FROM racing.actualizacion_racing
WHERE GRUPO = 'G3390'

COMMIT;

Viewing HR Schema Objects with SQL*Plus
--------------------------------------------
COLUMN OBJECT_NAME FORMAT A25
COLUMN OBJECT_TYPE FORMAT A25
SELECT OBJECT_NAME, OBJECT_TYPE FROM USER_OBJECTS
ORDER BY OBJECT_TYPE, OBJECT_NAME;

